In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import tkinter
%pylab inline
import pandas as pd
from itertools import cycle, islice
from functools import reduce
from scipy.stats import linregress
import scipy.stats as st
import numpy as np

# Study data files
games_details_path = "data_set/games_details.csv"
games_path = "data_set/games.csv"
teams_path = "data_set/teams.csv"


# Read the games data and the study results
games_details = pd.read_csv(games_details_path)
games = pd.read_csv(games_path)
teams = pd.read_csv(teams_path)

Populating the interactive namespace from numpy and matplotlib

FileNotFoundError: [Errno 2] No such file or directory: 'data_set/games_details.csv'

In [ ]:
games_details.head(3)

In [ ]:
games.head(3)

In [ ]:
#Merge the DataFrames
game_gamedetails_merged = pd.merge(games[['GAME_ID','GAME_DATE_EST','SEASON','HOME_TEAM_ID','HOME_TEAM_WINS']], games_details, right_on=['GAME_ID'],left_on=['GAME_ID'], how='inner')
game_gamedetails_merged.head(10)

In [ ]:
game_gamedetails_2018 = game_gamedetails_merged.loc[game_gamedetails_merged['SEASON'] == 2018]
game_gamedetails = game_gamedetails_2018.loc[game_gamedetails_2018['GAME_ID'] >= 21800001]

In [ ]:
team_point_agg = game_gamedetails.\
groupby(['TEAM_ID'])[['PTS']].\
agg('sum').reset_index()

team_point_agg_df = team_point_agg.sort_values(by='PTS', ascending=False)

team_point_agg_df.head(5)

In [ ]:
TEAM_ID_home = []
games_2018 = games.loc[games['SEASON']== 2018]
games_2018 = games_2018.loc[games_2018['GAME_ID'] >= 21800001]
games_2018.rename(columns={'HOME_TEAM_ID':'TEAM_ID'}, inplace =True)
home_wins = games_2018[['TEAM_ID','GAME_ID','HOME_TEAM_WINS']]
home_wins.head(3)

In [ ]:
home_wins_agg = home_wins.\
groupby(['TEAM_ID'])[['HOME_TEAM_WINS']].\
agg('sum').reset_index()

home_wins_agg_df = home_wins_agg.sort_values(by='HOME_TEAM_WINS', ascending=False)

home_wins_agg_df.head(5)

In [ ]:
home_loss = home_wins.loc[home_wins['HOME_TEAM_WINS'] == 0]
home_loss.head(3)

In [4]:
home_loss_agg = home_loss.\
groupby(['TEAM_ID'])[['HOME_TEAM_WINS']].\
agg('count').reset_index()

home_loss_agg_df = home_loss_agg.sort_values(by='HOME_TEAM_WINS', ascending=False)

home_loss_agg_df.head(5)

NameError: name 'home_loss' is not defined

In [11]:
## Which stadium has the most points/ total games.

In [12]:
teams.head(3)

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate

In [13]:
#Merge the DataFrames
team_Points = pd.merge(team_point_agg_df, teams [['TEAM_ID','CITY','ABBREVIATION','ARENA','NICKNAME']], right_on=['TEAM_ID'],left_on=['TEAM_ID'], how='inner')
team_Points.head(10)

,TEAM_ID,PTS,CITY,ABBREVIATION,ARENA,NICKNAME
0,1610612744,12161.0,Golden State,GSW,Chase Center,Warriors
1,1610612761,11942.0,Toronto,TOR,Scotiabank Arena,Raptors
2,1610612749,11378.0,Milwaukee,MIL,Fiserv Forum,Bucks
3,1610612757,11157.0,Portland,POR,Moda Center,Trail Blazers
4,1610612755,10749.0,Philadelphia,PHI,Wells Fargo Center,76ers
5,1610612743,10603.0,Denver,DEN,Pepsi Center,Nuggets
6,1610612745,10535.0,Houston,HOU,Toyota Center,Rockets
7,1610612738,10135.0,Boston,BOS,TD Garden,Celtics
8,1610612746,10130.0,Los Angeles,LAC,Staples Center,Clippers
9,1610612760,9913.0,Oklahoma City,OKC,Chesapeake Energy Arena,Thunder

In [21]:
#Merge the DataFrames
teams_city = pd.merge( team_Points ,home_wins_agg_df , on=['TEAM_ID'], how='left')
teams_city_df = pd.merge( teams_city ,home_loss_agg_df , on=['TEAM_ID'], how='left')
teams_city_df.rename(columns={'HOME_TEAM_WINS_x':'HOME_TEAM_WINS','HOME_TEAM_WINS_y':'HOME_TEAM_LOSS'}, inplace =True)
teams_city_df.head()

,TEAM_ID,PTS,CITY,ABBREVIATION,ARENA,NICKNAME,HOME_TEAM_WINS,HOME_TEAM_LOSS
0,1610612744,12161.0,Golden State,GSW,Chase Center,Warriors,36,16
1,1610612761,11942.0,Toronto,TOR,Scotiabank Arena,Raptors,41,13
2,1610612749,11378.0,Milwaukee,MIL,Fiserv Forum,Bucks,39,10
3,1610612757,11157.0,Portland,POR,Moda Center,Trail Blazers,37,12
4,1610612755,10749.0,Philadelphia,PHI,Wells Fargo Center,76ers,35,12

In [22]:
teams_city_df.to_csv("teams_city.csv", index=False)

In [2]:
print(teams_city_df.to_html())

NameError: name 'teams_city_df' is not defined