In [5]:
# from config import api_key
import pandas as pd
import numpy as np

In [6]:
# Data files
game_details_path = "games_details.csv"
games_path = "games.csv"
team_path = "teams.csv"

# Read the data files
game_details_data = pd.read_csv(game_details_path)
games_data = pd.read_csv(games_path)
teams_data = pd.read_csv(team_path)

In [11]:
game_details_data.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,42000102,1610612764,WAS,Washington,203078,Bradley Beal,F,NaN,34:36,14.0,...,0.0,4.0,4.0,3.0,1.0,0.0,1.0,0.0,33.0,-22.0
1,42000102,1610612764,WAS,Washington,1629060,Rui Hachimura,F,NaN,25:50,4.0,...,2.0,5.0,7.0,1.0,0.0,0.0,3.0,4.0,11.0,-6.0
2,42000102,1610612764,WAS,Washington,203458,Alex Len,C,NaN,12:11,3.0,...,3.0,2.0,5.0,0.0,1.0,0.0,0.0,2.0,6.0,-11.0
3,42000102,1610612764,WAS,Washington,203526,Raul Neto,G,NaN,19:19,2.0,...,1.0,2.0,3.0,1.0,0.0,0.0,0.0,2.0,4.0,-17.0
4,42000102,1610612764,WAS,Washington,201566,Russell Westbrook,G,NaN,29:07,2.0,...,2.0,4.0,6.0,11.0,0.0,0.0,4.0,0.0,10.0,-16.0

In [8]:
games_data.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2021-05-26,42000102,Final,1610612755,1610612764,2020,1610612755,120.0,0.557,0.684,...,26.0,45.0,1610612764,95.0,0.402,0.633,0.091,22.0,40.0,1
1,2021-05-26,42000132,Final,1610612752,1610612737,2020,1610612752,101.0,0.383,0.739,...,15.0,54.0,1610612737,92.0,0.369,0.818,0.273,17.0,41.0,1
2,2021-05-26,42000142,Final,1610612762,1610612763,2020,1610612762,141.0,0.544,0.774,...,28.0,42.0,1610612763,129.0,0.541,0.763,0.348,20.0,33.0,1
3,2021-05-25,42000112,Final,1610612751,1610612738,2020,1610612751,130.0,0.523,0.955,...,31.0,46.0,1610612738,108.0,0.424,0.783,0.353,23.0,43.0,1
4,2021-05-25,42000152,Final,1610612756,1610612747,2020,1610612756,102.0,0.465,0.933,...,21.0,31.0,1610612747,109.0,0.450,0.871,0.303,24.0,39.0,0

In [9]:
teams_data.head()

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends

In [12]:
# merging games details data with games data

merged = game_details_data.merge(games_data, on='GAME_ID')
merged

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,42000102,1610612764,WAS,Washington,203078,Bradley Beal,F,NaN,34:36,14.0,...,26.0,45.0,1610612764,95.0,0.402,0.633,0.091,22.0,40.0,1
1,42000102,1610612764,WAS,Washington,1629060,Rui Hachimura,F,NaN,25:50,4.0,...,26.0,45.0,1610612764,95.0,0.402,0.633,0.091,22.0,40.0,1
2,42000102,1610612764,WAS,Washington,203458,Alex Len,C,NaN,12:11,3.0,...,26.0,45.0,1610612764,95.0,0.402,0.633,0.091,22.0,40.0,1
3,42000102,1610612764,WAS,Washington,203526,Raul Neto,G,NaN,19:19,2.0,...,26.0,45.0,1610612764,95.0,0.402,0.633,0.091,22.0,40.0,1
4,42000102,1610612764,WAS,Washington,201566,Russell Westbrook,G,NaN,29:07,2.0,...,26.0,45.0,1610612764,95.0,0.402,0.633,0.091,22.0,40.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617387,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,NaN,NaN,19,4.0,...,21.0,40.0,1610612743,106.0,0.532,0.615,0.471,25.0,34.0,0
617388,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,NaN,NaN,23,7.0,...,21.0,40.0,1610612743,106.0,0.532,0.615,0.471,25.0,34.0,0
617389,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,NaN,NaN,15,3.0,...,21.0,40.0,1610612743,106.0,0.532,0.615,0.471,25.0,34.0,0
617390,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,NaN,NaN,19,1.0,...,21.0,40.0,1610612743,106.0,0.532,0.615,0.471,25.0,34.0,0
617391,11200005,1610612743,DEN,Denver,201951,Ty Lawson,NaN,NaN,27,3.0,...,21.0,40.0,1610612743,106.0,0.532,0.615,0.471,25.0,34.0,0

In [13]:
# merging teams data to merged data

final_merged = merged.merge(teams_data, on='TEAM_ID')
final_merged

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,42000102,1610612764,WAS,Washington,203078,Bradley Beal,F,NaN,34:36,14.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
1,42000102,1610612764,WAS,Washington,1629060,Rui Hachimura,F,NaN,25:50,4.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
2,42000102,1610612764,WAS,Washington,203458,Alex Len,C,NaN,12:11,3.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
3,42000102,1610612764,WAS,Washington,203526,Raul Neto,G,NaN,19:19,2.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
4,42000102,1610612764,WAS,Washington,201566,Russell Westbrook,G,NaN,29:07,2.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617387,11200021,1610612758,SAC,Sacramento,201977,Marcus Thornton,NaN,NaN,24,3.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617388,11200021,1610612758,SAC,Sacramento,203080,Thomas Robinson,NaN,NaN,29,4.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617389,11200021,1610612758,SAC,Sacramento,203183,Tony Mitchell,NaN,NaN,5,0.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617390,11200021,1610612758,SAC,Sacramento,201936,Tyreke Evans,NaN,NaN,24,4.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617391,11200021,1610612758,SAC,Sacramento,203186,Willie Reed,NaN,NaN,2,0.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings

In [14]:
final_merged.to_csv("output.csv", index=False)

PermissionError: [Errno 13] Permission denied

In [15]:
#only focus on season 2018
mask = final_merged.SEASON != 2018
mask1 = final_merged[mask]
mask1

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,42000102,1610612764,WAS,Washington,203078,Bradley Beal,F,NaN,34:36,14.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
1,42000102,1610612764,WAS,Washington,1629060,Rui Hachimura,F,NaN,25:50,4.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
2,42000102,1610612764,WAS,Washington,203458,Alex Len,C,NaN,12:11,3.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
3,42000102,1610612764,WAS,Washington,203526,Raul Neto,G,NaN,19:19,2.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
4,42000102,1610612764,WAS,Washington,201566,Russell Westbrook,G,NaN,29:07,2.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617387,11200021,1610612758,SAC,Sacramento,201977,Marcus Thornton,NaN,NaN,24,3.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617388,11200021,1610612758,SAC,Sacramento,203080,Thomas Robinson,NaN,NaN,29,4.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617389,11200021,1610612758,SAC,Sacramento,203183,Tony Mitchell,NaN,NaN,5,0.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617390,11200021,1610612758,SAC,Sacramento,201936,Tyreke Evans,NaN,NaN,24,4.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617391,11200021,1610612758,SAC,Sacramento,203186,Willie Reed,NaN,NaN,2,0.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings

In [18]:
# excluding pre-season games
new_data = mask1[mask1["GAME_ID"] > 20000000]

new_data

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,42000102,1610612764,WAS,Washington,203078,Bradley Beal,F,NaN,34:36,14.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
1,42000102,1610612764,WAS,Washington,1629060,Rui Hachimura,F,NaN,25:50,4.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
2,42000102,1610612764,WAS,Washington,203458,Alex Len,C,NaN,12:11,3.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
3,42000102,1610612764,WAS,Washington,203526,Raul Neto,G,NaN,19:19,2.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
4,42000102,1610612764,WAS,Washington,201566,Russell Westbrook,G,NaN,29:07,2.0,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Tommy Sheppard,Scott Brooks,Capital City Go-Go
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617294,21200007,1610612758,SAC,Sacramento,101128,Francisco Garcia,NaN,NaN,7:40,2.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617295,21200007,1610612758,SAC,Sacramento,101236,Chuck Hayes,NaN,NaN,17:43,1.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617296,21200007,1610612758,SAC,Sacramento,202690,Jimmer Fredette,NaN,NaN,0:06,0.0,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617297,21200007,1610612758,SAC,Sacramento,202715,Tyler Honeycutt,NaN,DNP - Coach's Decision,NaN,NaN,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings
617298,21200007,1610612758,SAC,Sacramento,2566,Travis Outlaw,NaN,DNP - Coach's Decision,NaN,NaN,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Vlade Divac,Luke Walton,Stockton Kings

In [ ]:
# stadium has the most points/wins/ total games